textures:
  bundles:
    - name: 'town-view'
      assets:
        - name: 'town-bg'
          srcs: 'city-cbb.png'
        - name: 'town-collmap'
          srcs: 'city-collmap.png'
        - name: 'player-1'
          srcs: 'player-1.json'
        - name: 'player-2'
          srcs: 'player-2.json'
        - name: 'player-3'
          srcs: 'player-3.json'
        - name: 'npcs-demo'
          srcs: 'npcs-demo.json'
        - name: 'mood-balloon'
          srcs: 'mood-balloon.json'
        - name: 'map-markers'
          srcs: 'map-markers.json'
        - name: 'icons'
          srcs: 'icons.json'
